config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'

  get 'about', to: 'welcome#about'
  get 'contact', to: 'contacts#new'
  get 'contacts', to: 'contacts#catch_contacts'
  get 'meabuilder', to: 'measkills#main'
  get 'meabuilder2', to: 'welcome#measkills'
  get 'tech_theme', to: 'welcome#tech_theme'

  resources :contacts, only: [:new, :create]

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contacted From sharperprogrammer.com",
      :to => "sharperprogrammer@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/measkill.rb
class Measkill < ActiveRecord::Base
  
end

app/models/thought.rb
class Thought < ActiveRecord::Base
  
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 100 }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash[:success] = 'Thank you for your message. I will be in touch soon!'
			redirect_to contact_path
    else
      flash[:danger] = 'Error: Could not send message.'
      render :new
    end
  end
	
	def catch_contacts
		redirect_to contact_path
	end
	
end

app/controllers/measkills_controller.rb
class MeaskillsController < ApplicationController
  
  def main
    @measkills = Measkill.all

    if params[:skillfilter] == "increase-melee-atk"
      @selectedskills = Array.new
      @measkills.each do |measkill|
        if measkill.meleeatkup == true
          @selectedskills.push(measkill)
        end
      end
    elsif params[:skillfilter] == "boost-shield-dmg"
      @selectedskills = Array.new
      @measkills.each do |measkill|
        if measkill.boostshielddmg == true
          @selectedskills.push(measkill)
        end
      end
    elsif params[:skillfilter] == "boost-armor-dmg"
      @selectedskills = Array.new
      @measkills.each do |measkill|
        if measkill.boostarmordmg == true
          @selectedskills.push(measkill)
        end
      end
    else
      @selectedskills = Array.new
#      @selectedskills.push(@measkills.find(7))
#      @selectedskills.push(@measkills.find(10))
    end
  end
  
end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController
  
  def index
    @thoughts = Thought.all
  end

  def new 
    @thought = Thought.new
  end
  
  def create
    # render plain: params[:thought].inspect
    
    @thought = Thought.new(thought_params)
    if @thought.save
      flash[:success] = "Thought was successfully created"
      # this will go through the route (which you can see from the console with 
      # ‘rake routes’) with prefix: ‘thought’.  
      redirect_to thought_path(@thought)
    else
      render 'new'
    end
  end
  
  def show
    @thought = Thought.find(params[:id])
  end
  
  def edit
    @thought = Thought.find(params[:id])
  end
  
  def destroy
    @thought = Thought.find(params[:id])
    @thought.destroy
    flash[:danger] = "Thought was successfully deleted."
    redirect_to thoughts_path
  end

  def update
    @thought = Thought.find(params[:id])
    if @thought.update(thought_params)
      flash[:success] = "Thought was successfully updated."
      redirect_to thought_path(@thought)
    else 
      render 'edit'
    end
  end
  
  private 
  def thought_params
    # this allows us to use the title and description fields that are in params
    params.require(:thought).permit(:title, :description)
    
  end

  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    # since there is no code in this Action, it will merely load home.html.erb
  def home

  end

  # since there is no code in this Action, it will merely load about.html.erb
  def about

  end

  def measkills
    redirect_to "http://www.sharperprogrammer.com/meabuilder2"
  end

  def tech_theme
    redirect_to "http://www.sharperprogrammer.com/tech_theme"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<h1 align="center">Contact me...</h1>

<div class="row">
  <div class="col-md-12">
    
    <%= form_for(@contact, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :name %>
      </div>
      <div class="col-sm-8">
        <%= f.text_field :name, class: "form-control", placeholder: "Your full name", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :email %>
      </div>
      <div class="col-sm-8">
        <%= f.text_field :email, class: "form-control", placeholder: "Your email address", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :message %>
      </div>
      <div class="col-sm-8">
        <%= f.text_area :message, rows: 10, class: "form-control", placeholder: "Enter message here." %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit 'Send Message', class: "btn btn-primary btn-lg" %>
      </div>
    </div>
    <% end %>

  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
   <footer class="footer">
      <small>
        Copyright &copy; 2018 <a href="https://www.sharperprogrammer.com">Seth Harper</a>
         - Last Updated 7:03am, June 7th, 2019
     </small>
     <nav>
       <ul>
         <li><%= link_to "Home", root_path %></li>
         <li><%= link_to "About", about_path %></li>
         <li><%= link_to "Tech Theme", tech_theme_path %></li>
				 <li><%= link_to "MEA:Builder", meabuilder_path %></li>
         <li><%= link_to "Contact", contact_path %></li>
         <li><%= link_to "Folding@Home", 'http://fah-web2.stanford.edu/cgi-bin/main.py?qtype=teampage&teamnum=233995' %></li>
       </ul>
     </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">×</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Seth Harper", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path, class: "nav-link" %></li>
        <li><%= link_to "About", about_path, class: "nav-link" %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Projects<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Tech Theme Website", tech_theme_path %></li>
            <li><%= link_to "MEA:Builder", meabuilder_path, class: "nav-link" %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav">
        <li><%= link_to "Contact", contact_path, class: "nav-link" %></li>
        <li><%= link_to "Folding@Home", 'http://fah-web2.stanford.edu/cgi-bin/main.py?qtype=teampage&teamnum=171089', class: "nav-link" %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seth Harper - Programmer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  
</body>
</html>

app/views/measkills/main.html.erb
<div align="center">

  <div class="meaimage">
  </div>
  
<div class="measkills-links">
  <%= link_to "Skills that boost Melee Dmg", meabuilder_path(:skillfilter => "increase-melee-atk") %> |
  <%= link_to "Boost Shield Damage", meabuilder_path(:skillfilter => "boost-shield-dmg") %> |
  <%= link_to "Boost Armor Damage", meabuilder_path(:skillfilter => "boost-armor-dmg") %>
</div>
  
  <table>
    <tr>
      <th>Combat</th>
      <th>Biotics</th>
      <th>Tech</th>
    </tr>
    <% @measkills.each do |measkill| %>
      <% if measkill.category == "Combat" %>
      <tr>
        <td>
          <% if @selectedskills.include?(measkill) %>
          <strong>
          <% end %>
            <%= measkill.name %>
          <% if @selectedskills.include?(measkill) %>
          </strong>
          <% end %>
        </td>
      <% elsif measkill.category == "Biotics" %>
        <td>
          <% if @selectedskills.include?(measkill) %>
          <strong>
          <% end %>
            <%= measkill.name %>
          <% if @selectedskills.include?(measkill) %>
          </strong>
          <% end %>
        </td>
      <% else %>
        <td>
          <% if @selectedskills.include?(measkill) %>
          <strong>
          <% end %>
            <%= measkill.name %>
          <% if @selectedskills.include?(measkill) %>
          </strong>
          <% end %>
        </td>
      </tr>
      <% end %>
    <% end %>
  </table>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this <%= obj.class %> from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/welcome/about.html.erb
<!DOCTYPE html>
<html>
<title>Test Home Page</title>
<body>

  <div class="about">
    
  
    <h1>Who dis?</h2>
    <p>I'm Seth Harper. I've been a programmer for 7 years. 
        I have an education in Video Game Development, 
			  I recently started dabbling in Web Development, and I have 
			  a passion for programming. This site is a collection of my ongoing 
        projects.  Feel free to take a look around!</p>
    <hr>
    <div class="currently-learning">
      <h2 style="font-size:2em;">Things I am working on:</h2>
      <ul>
        <li>Ruby on Rails - MVC Framework based on a fun to learn language.</li>
        <li>Javascript/CSS - To help me make my website look pretty.</li>
        <li>Apache - HTTP Server</li> 
        <li>Passenger - Web Application Server by Phusion</li>
        <li>Nginx - Reverse Proxy Server</li>
				<li>Linux Administration - Managing my server</li>
				<li>Ethical Hacking - Cyber Security</li>
				<li>Unity - 3D Game Engine (On Hold)</li>
				<li>Blender - 3D Modeling (On Hold)</li>
      </ul>
    </div>
    <hr />
    <p>
      Stay tuned to see what I whip up with these nifty tools!
    </p>
  </div>
</body>
</html>

app/views/welcome/home.html.erb
<!DOCTYPE html>
<html>
<title>Seth Harper - Programmer</title>
<body>

  <div class="jumbotron jumbotron-home center-me">
    <h1 class="white-text">"Mudhole? Slimy? My home this is!" -Yoda</h1>

  </div>
  
</body>
</html>